@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwNDU3MzcyLCJleHAiOjE3NjA0NTc5NzJ9.5MBMmfIDy2ZknKh1SLlYDVdyaHbuwmc1oYMXK4ulkMs


### Obtener todos los pagos (SIN token)
GET {{baseUrl}}/api/payments

### Obtener pago por ID (SIN token)
GET {{baseUrl}}/api/payments/1

### Crear un pago (SIN token)
POST {{baseUrl}}/api/payments
Content-Type: application/json

{
  "id_order": 2,
  "method": "PSE",
  "amount": 250000,
  "status": "ACTIVE"
}

### Actualizar un pago (SIN token)
PATCH {{baseUrl}}/api/payments/1
Content-Type: application/json

{
  "method": "PayPal"
}

### Eliminar un pago lógicamente (SIN token)
DELETE {{baseUrl}}/api/payments/1/logic

### Eliminar un pago físicamente (SIN token)
    DELETE {{baseUrl}}/api/payments/1



### ================== RUTAS con AUTENTICACIÓN ==================

### Obtener todos los pagos
GET {{baseUrl}}/api/Payments
Authorization: Bearer {{token}}

### Obtener pago por ID
GET {{baseUrl}}/api/Payments/1
Authorization: Bearer {{token}}

### Crear un pago
POST {{baseUrl}}/api/Payments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_order": 1,
  "method": "Credit Card",
  "amount": 119000,
  "status": "ACTIVE"
}

### Actualizar un pago
PATCH {{baseUrl}}/api/Payments/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "method": "Cash"
}

### Eliminar un pago lógicamente
DELETE {{baseUrl}}/api/Payments/1/logic
Authorization: Bearer {{token}}

### Eliminar un pago físicamente
DELETE {{baseUrl}}/api/Payments/1
Authorization: Bearer {{token}}
